#!/bin/bash

old_names=(
    "gtests/net/tcp/accecn/close/close-local-close-then-remote-fin.pkt"
    "gtests/net/tcp/accecn/counters/3rd-ack-lost-data-ce.pkt"
    "gtests/net/tcp/accecn/counters/delivered-2ndlargeack.pkt"
    "gtests/net/tcp/accecn/counters/delivered-falseoverflow-detect.pkt"
    "gtests/net/tcp/accecn/counters/delivered-largeack.pkt"
    "gtests/net/tcp/accecn/counters/delivered-largeack2.pkt"
    "gtests/net/tcp/accecn/counters/delivered-maxack.pkt"
    "gtests/net/tcp/accecn/counters/delivered-updates.pkt"
    "gtests/net/tcp/accecn/counters/ecn-field-updates-opt.pkt"
    "gtests/net/tcp/accecn/counters/noprogress.pkt"
    "gtests/net/tcp/accecn/counters/sack-space-grab-with-ts.pkt"
    "gtests/net/tcp/accecn/counters/sack-space-grab.pkt"
    "gtests/net/tcp/accecn/counters/tsnoprogress.pkt"
    "gtests/net/tcp/accecn/counters/tsprogress.pkt"
    "gtests/net/tcp/accecn/fallback/acc_ecn_disabled.pkt"
    "gtests/net/tcp/accecn/fallback/accecn-to-rfc3168.pkt"
    "gtests/net/tcp/accecn/fallback/client_accecn_options_drop.pkt"
    "gtests/net/tcp/accecn/fallback/client_accecn_options_lost.pkt"
    "gtests/net/tcp/accecn/fallback/ecn3.pkt"
    "gtests/net/tcp/accecn/fallback/ipflags-drop.pkt"
    "gtests/net/tcp/accecn/fallback/listen-opt-drop.pkt"
    "gtests/net/tcp/accecn/fallback/multiple_syn_ack_drop.pkt"
    "gtests/net/tcp/accecn/fallback/multiple_syn_drop.pkt"
    "gtests/net/tcp/accecn/fallback/negotiation-bleach.pkt"
    "gtests/net/tcp/accecn/fallback/rfc3168-to-fallback.pkt"
    "gtests/net/tcp/accecn/fallback/rfc3168-to-rfc3168.pkt"
    "gtests/net/tcp/accecn/fallback/syn_ace_flags_acked_after_retransmit.pkt"
    "gtests/net/tcp/accecn/fallback/syn_ace_flags_drop.pkt"
    "gtests/net/tcp/accecn/fallback/syn_ack_ace_flags_acked_after_retransmit.pkt"
    "gtests/net/tcp/accecn/fallback/syn_ack_ace_flags_drop.pkt"
    "gtests/net/tcp/accecn/negotiation/3rd-ack-after-synack-rxmt.pkt"
    "gtests/net/tcp/accecn/negotiation/3rd-dups.pkt"
    "gtests/net/tcp/accecn/negotiation/accecn_then_notecn_syn.pkt"
    "gtests/net/tcp/accecn/negotiation/clientside-disabled.pkt"
    "gtests/net/tcp/accecn/negotiation/negotiation-connect.pkt"
    "gtests/net/tcp/accecn/negotiation/negotiation-listen.pkt"
    "gtests/net/tcp/accecn/negotiation/negotiation-noopt-connect.pkt"
    "gtests/net/tcp/accecn/negotiation/negotiation-optenable.pkt"
    "gtests/net/tcp/accecn/negotiation/no-ecn-after-acc-ecn.pkt"
    "gtests/net/tcp/accecn/negotiation/noopt.pkt"
    "gtests/net/tcp/accecn/negotiation/notecn_then_accecn_syn.pkt"
    "gtests/net/tcp/accecn/negotiation/serverside-accecn-disabled1.pkt"
    "gtests/net/tcp/accecn/negotiation/serverside-accecn-disabled2.pkt"
    "gtests/net/tcp/accecn/negotiation/serverside-broken.pkt"
    "gtests/net/tcp/accecn/negotiation/serverside-ecn-disabled.pkt"
    "gtests/net/tcp/accecn/negotiation/serverside-only.pkt"
    "gtests/net/tcp/accecn/negotiation/synack-rexmit.pkt"
    "gtests/net/tcp/accecn/negotiation/synack-rxmt.pkt"
    "gtests/net/tcp/accecn/reflector/2nd-data-as-first-connect.pkt"
    "gtests/net/tcp/accecn/reflector/2nd-data-as-first.pkt"
    "gtests/net/tcp/accecn/reflector/3rd-ack-ce-updates-received_ce.pkt"
    "gtests/net/tcp/accecn/reflector/syn-ce.pkt"
    "gtests/net/tcp/accecn/reflector/syn-ect0.pkt"
    "gtests/net/tcp/accecn/reflector/syn-ect1.pkt"
    "gtests/net/tcp/accecn/reflector/synack-ce-updates-delivered-ce.pkt"
    "gtests/net/tcp/accecn/reflector/synack-ce.pkt"
    "gtests/net/tcp/accecn/reflector/synack-ect0.pkt"
    "gtests/net/tcp/accecn/reflector/synack-ect1.pkt"
)

new_names=(
    "gtests/net/tcp/accecn/close/tcp_accecn_close_local_close_then_remote_fin.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_3rd_ack_lost_data_ce.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_delivered_2ndlargeack.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_delivered_falseoverflow_detect.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_delivered_largeack.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_delivered_largeack2.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_delivered_maxack.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_delivered_updates.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_ecn_field_updates_opt.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_noprogress.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_sack_space_grab_with_ts.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_sack_space_grab.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_tsnoprogress.pkt"
    "gtests/net/tcp/accecn/counters/tcp_accecn_tsprogress.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_acc_ecn_disabled.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_accecn_to_rfc3168.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_client_accecn_options_drop.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_client_accecn_options_lost.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_ecn3.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_ipflags_drop.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_listen_opt_drop.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_multiple_syn_ack_drop.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_multiple_syn_drop.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_negotiation_bleach.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_rfc3168_to_fallback.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_rfc3168_to_rfc3168.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_syn_ace_flags_acked_after_retransmit.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_syn_ace_flags_drop.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_syn_ack_ace_flags_acked_after_retransmit.pkt"
    "gtests/net/tcp/accecn/fallback/tcp_accecn_syn_ack_ace_flags_drop.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_3rd_ack_after_synack_rxmt.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_3rd_dups.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_accecn_then_notecn_syn.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_clientside_disabled.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_negotiation_connect.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_negotiation_listen.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_negotiation_noopt_connect.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_negotiation_optenable.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_no_ecn_after_acc_ecn.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_noopt.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_notecn_then_accecn_syn.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_serverside_accecn_disabled1.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_serverside_accecn_disabled2.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_serverside_broken.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_serverside_ecn_disabled.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_serverside_only.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_synack_rexmit.pkt"
    "gtests/net/tcp/accecn/negotiation/tcp_accecn_synack_rxmt.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_2nd_data_as_first_connect.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_2nd_data_as_first.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_3rd_ack_ce_updates_received_ce.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_syn_ce.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_syn_ect0.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_syn_ect1.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_synack_ce_updates_delivered_ce.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_synack_ce.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_synack_ect0.pkt"
    "gtests/net/tcp/accecn/reflector/tcp_accecn_synack_ect1.pkt"
)

# Check arrays have same length
if [ ${#old_names[@]} -ne ${#new_names[@]} ]; then
    echo "Error: Arrays must have the same length" >&2
    exit 1
fi

# Iterate and rename
for i in "${!old_names[@]}"; do
    old="${old_names[$i]}"
    new="${new_names[$i]}"
    if [ -e "$old" ]; then
        mv "$old" "$new"
        echo "Renamed $old -> $new"
    else
        echo "Warning: $old does not exist"
    fi
done
